services:
  eth-blockchain:
    ports:
      - 8545:8545

  chainlink-node:
    env_file:
        - ./services/chainlink-node/.env.local
    ports:
      - 6688:6688
    restart: on-failure
    
  node-controller:
    environment:
      - PORT=3001
      - WEB3_CONNECTION_URL=ws://eth-blockchain:8545
    ports:
      - 3001:3001
