networks:
  blockchain:
    driver: bridge

volumes:
  chainlink-node-data:
    driver: local
    driver_opts:
      type: none
      device: "./data/chainlink-node"
      o: bind

  eth_blockchain_accounts_debug:
    driver: local
    driver_opts:
      type: none
      device: "./data/eth-blockchain/accounts"
      o: bind

services:
  eth-blockchain:
    image: trufflesuite/ganache-cli:v6.12.2
    networks:
      - blockchain
    volumes:
      - ./data/eth-blockchain/accounts/accounts.json:/app/accounts.json
    command: --port 8545 --chainId 1337 --forkCacheSize 268435456 --debug --verbose --mnemonic "$HD_WALLET_MNEMONIC" --account_keys_path accounts.json
    container_name: remune_eth_blockhain

  db-chainlink-node:
    image: postgres:14.2-alpine
    env_file:
      - ./services/db-chainlink-node/.env
    networks:
      - blockchain
    container_name: remune_db_chainlink_node

  chainlink-node:
    image: smartcontract/chainlink:1.1.1
    volumes:
      - ./services/chainlink-node/.password:/chainlink/.password
      - ./services/chainlink-node/.api:/chainlink/.api
      - chainlink-node-data:/chainlink
    networks:
      - blockchain
    command: local node -p /chainlink/.password -a /chainlink/.api
    container_name: remune_chainlink_node

  contracts-workbench:
    build:
      context: ./services/contracts-workbench
    image: contracts-workbench:latest
    networks:
      - blockchain
    command: tail /dev/null -f
    container_name: remune_contracts_workbench
