networks:
  blockchain:
    driver: bridge
  
  web:
    driver: bridge
      
services:
  node-controller:
    build:
      context: ./services/node-controller
    image: node-controller:latest
    networks:
      - blockchain
      - web
    container_name: devmune_node_controller

  devmune_ui:
    build:
      context: ./services/devmune-ui
    image: devmune-ui:latest
    environment:
      - DEVMUNE_HOST=${DEVMUNE_HOST}
    networks:
      - blockchain
      - web
    container_name: devmune_ui
